FROM arm32v7/rust:1.31 as builder

WORKDIR /usr/src/myapp
COPY . .
RUN cargo build --release


FROM arm32v6/alpine:3.7

COPY --from=builder /usr/src/myapp/target/release/quadsbot /quadsbot

CMD ["/quadsbot"]
